name: Go Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go 1.24.2
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'

  build:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            GOOS: linux
            GOARCH: amd64
          - platform: linux/arm64
            GOOS: linux
            GOARCH: arm64
          - platform: windows/amd64
            GOOS: windows
            GOARCH: amd64
            ext: .exe

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go 1.24.2
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'

      - name: Build Binary
        env:
          GOOS: ${{ matrix.GOOS }}
          GOARCH: ${{ matrix.GOARCH }}
          CGO_ENABLED: 0
        run: |
          output_name="ai-${{ matrix.GOOS }}-${{ matrix.GOARCH }}${{ matrix.ext || '' }}"
          go build -o $output_name ./cmd/ai/main.go
          echo "BUILD_PATH=$output_name" >> $GITHUB_ENV

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform }}-binary
          path: ${{ env.BUILD_PATH }}
